allowBuilds:
  sharp: true
minimumReleaseAgeExclude:
  - '@supabase/auth-js@2.110.0'
  - '@supabase/functions-js@2.110.0'
  - '@supabase/postgrest-js@2.110.0'
  - '@supabase/realtime-js@2.110.0'
  - '@supabase/storage-js@2.110.0'
  - '@supabase/supabase-js@2.110.0'
  - react-icons@5.7.0
  - '@supabase/cli-darwin-arm64@2.109.0'
  - '@supabase/cli-darwin-x64@2.109.0'
  - '@supabase/cli-linux-arm64-musl@2.109.0'
  - '@supabase/cli-linux-arm64@2.109.0'
  - '@supabase/cli-linux-x64-musl@2.109.0'
  - '@supabase/cli-linux-x64@2.109.0'
  - '@supabase/cli-windows-arm64@2.109.0'
  - '@supabase/cli-windows-x64@2.109.0'
  - supabase@2.109.0
